inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - '**/Gemfile'
    - 'spec/dummy/**/*'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 45

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false
