#!/usr/bin/env ruby
# frozen_string_literal: true

require ENV['APP_PATH'] || File.join(File.expand_path('.'), 'config', 'application')

Rails.application.initialize!
Rails.application.eager_load!

begin
  Artery::Sync.new.execute ARGV.map(&:strip)
ensure
  Artery.clear_synchronizing_subscriptions!
end
