#!/usr/bin/env ruby
# frozen_string_literal: true

require ENV['APP_PATH'] || File.join(File.expand_path('.'), 'config', 'application')

Rails.application.initialize!
Rails.application.eager_load!

Artery.use_backend :nats # redefine because only default works in worker

Artery::Worker.new.run ARGV.map(&:strip)
